'use client';

import Image from 'next/image';

/**
 * Map of background IDs → pixel art PNGs.
 * Generated by scripts/pixelize.ts from reference photos.
 * These are the SOLE visual — no CSS overlay shapes.
 */
const PIXEL_BGS: Record<string, string> = {
  bg_bedroom_night: '/vn-assets/backgrounds/pixel/bedroom_pixel.png',
  bg_street_flood: '/vn-assets/backgrounds/pixel/flood_pixel.png',
  bg_evacuation_center: '/vn-assets/backgrounds/pixel/evac_pixel.png',
  bg_classroom: '/vn-assets/backgrounds/pixel/classroom_pixel.png',
};

/**
 * Scene backgrounds — pixel art PNGs with a vignette overlay.
 *
 * The pixel art images (pixelized from reference photos) already contain
 * all scene elements (windows, furniture, streets, buildings, chalkboards).
 * NO procedural CSS shapes are drawn — those would create the "horror
 * silhouette" look described in PIXEL_ART_GUIDE §5.0.
 *
 * Fallback gradient is used only when no PNG is available (e.g. bg_black).
 */

interface BgDef {
  gradient: string;
}

const BG_MAP: Record<string, BgDef> = {
  bg_black: {
    gradient: 'bg-storm-bg',
  },
  bg_bedroom_night: {
    gradient: 'bg-gradient-to-b from-storm-bg via-[#15131A] to-[#1A1720]',
  },
  bg_street_flood: {
    gradient: 'bg-gradient-to-b from-[#1a1c23] via-[#1f2833] to-[#2a3441]',
  },
  bg_evacuation_center: {
    gradient: 'bg-gradient-to-b from-[#1C1916] via-[#242128] to-[#2C2930]',
  },
  bg_classroom: {
    gradient: 'bg-gradient-to-b from-[#1A1720] via-[#1E1B24] to-[#22202A]',
  },
};

interface BackgroundProps {
  backgroundId?: string;
  children?: React.ReactNode;
}

export function Background({ backgroundId, children }: BackgroundProps) {
  const config = backgroundId ? BG_MAP[backgroundId] : undefined;
  const pngPath = backgroundId ? PIXEL_BGS[backgroundId] : undefined;
  const gradientClass = config?.gradient ?? 'bg-storm-bg';

  return (
    <div className={`absolute inset-0 ${gradientClass} transition-all duration-700 ease-in-out`}>
      {/* Pixel art PNG background — the sole visual */}
      {pngPath && (
        <Image
          src={pngPath}
          alt="Background"
          fill
          className="object-cover image-pixel"
          priority
          unoptimized
        />
      )}

      {/* Subtle pixel grid texture (very faint, adds retro feel) */}
      <div
        className="absolute inset-0 opacity-[0.03] pointer-events-none"
        style={{
          backgroundImage:
            'repeating-linear-gradient(0deg, transparent, transparent 3px, rgba(255,255,255,0.02) 3px, rgba(255,255,255,0.02) 4px),' +
            'repeating-linear-gradient(90deg, transparent, transparent 3px, rgba(255,255,255,0.02) 3px, rgba(255,255,255,0.02) 4px)',
        }}
      />

      {/* Vignette — darkens edges for atmosphere */}
      <div
        className="absolute inset-0 pointer-events-none"
        style={{
          background: 'radial-gradient(ellipse at center, transparent 50%, rgba(0,0,0,0.5) 100%)',
        }}
      />

      {children}
    </div>
  );
}
