'use client';

import Image from 'next/image';

interface CharacterSpriteProps {
  spriteId?: string;
  speaker?: string;
}

/**
 * Map of character sprite sheets → pixel art PNGs.
 * Generated by scripts/pixelize.ts from reference photos.
 */
const PIXEL_PNGS: Record<string, string> = {
  lola_worried: '/vn-assets/characters/lola/pixel/lola_pixel.png',
  maria_urgent: '/vn-assets/characters/maria/pixel/maria_pixel.png',
  maria_skeptical: '/vn-assets/characters/maria/pixel/maria_pixel.png', // same base
  jeff_concerned: '/vn-assets/characters/jeff/pixel/jeff_pixel.png',
};

/**
 * Pixel art character sprites — CSS-based placeholders using colored blocks.
 * Each character is a simple 12x16 pixel figure drawn with small divs.
 * Falls back to PNG pixel art when available.
 */
const CHARACTER_PIXELS: Record<string, { pixels: string[][]; label: string }> = {
  lola_worried: {
    label: 'Lola',
    pixels: [
      // Hair (b=base, c=shadow)
      '  bb  '.split(''),
      ' bbbb '.split(''),
      'bbbbbb'.split(''),
      'b3113b'.split(''), // hair framing face (3=skin)
      '38  83'.split(''), // eyes (8=white)
      '3 9 93'.split(''), // iris (9=brown)
      '322223'.split(''), // cheeks/nose
      'bbbbbb'.split(''), // hair bottom
      'bbbbbb'.split(''), // neck shadow
      '  ee  '.split(''), // dress top (e=base)
      ' eeee '.split(''),
      'eeeeee'.split(''),
      'eh  he'.split(''), // arms (h=highlight)
      ' eeee '.split(''),
      '  gg  '.split(''), // dress bottom
      '  gg  '.split(''),
    ],
  },
  maria_urgent: {
    label: 'Maria',
    pixels: [
      // Hair (i=base, j=shadow)
      '  ii  '.split(''),
      ' iiii '.split(''),
      'iiiiii'.split(''),
      'i3113i'.split(''), // hair framing face
      '38  83'.split(''), // eyes
      '3 9 93'.split(''), // iris
      '3a aa3'.split(''), // blush (a=lip/blush)
      'iiiiii'.split(''), // hair bottom
      'iiiiii'.split(''), // neck
      '  ww  '.split(''), // uniform top (w=white)
      ' wwww '.split(''),
      'wwwwww'.split(''),
      'wx  xw'.split(''), // arms (x=white shadow)
      ' wwwww'.split(''),
      '  ll  '.split(''), // skirt (l=navy)
      '  ll  '.split(''),
    ],
  },
  maria_skeptical: {
    label: 'Maria',
    pixels: [
      // Same as maria_urgent but with skeptical squint
      '  ii  '.split(''),
      ' iiii '.split(''),
      'iiiiii'.split(''),
      'i3113i'.split(''),
      '38 8 3'.split(''), // skeptical squint
      '3 9 93'.split(''),
      '3a aa3'.split(''),
      'iiiiii'.split(''),
      'iiiiii'.split(''),
      '  ww  '.split(''),
      ' wwww '.split(''),
      'wwwwww'.split(''),
      'wx  xw'.split(''),
      ' wwwww'.split(''),
      '  ll  '.split(''),
      '  ll  '.split(''),
    ],
  },
  jeff_concerned: {
    label: 'Jeff',
    pixels: [
      // Hair (p=base, q=shadow)
      '  pp  '.split(''),
      ' pppp '.split(''),
      'pppppp'.split(''),
      'p3113p'.split(''), // hair + face
      '38  83'.split(''), // eyes
      '39 9 3'.split(''), // concerned brow
      '322223'.split(''),
      'pppppp'.split(''), // hair bottom
      'p  pp '.split(''), // collar
      '  ww  '.split(''), // uniform (w=white)
      ' wwww '.split(''),
      'wwwwww'.split(''),
      'wx  xw'.split(''),
      ' wwwww'.split(''),
      '  ss  '.split(''), // pants (s=blue-gray)
      '  ss  '.split(''),
    ],
  },
};

/**
 * Expanded color palette — matching the locked 24-30 color palette files.
 * Used as CSS fallback when pixel PNGs aren't available.
 * See public/vn-assets/characters/[character]/palette.json for the full palettes.
 */
const COLOR_MAP: Record<string, string> = {
  '0': '#1A1815', // Outline (shared across all characters)

  // Skin tones (warm Filipino skin — 7 tones)
  '1': '#F5E6D0', '2': '#EDD4B8', '3': '#E4C8A8',
  '4': '#D8B890', '5': '#CCAC84', '6': '#C09C74', '7': '#B48C64',

  // Eye/Lip accents
  '8': '#F0ECE4', // Eye white / highlight
  '9': '#4A3A28', // Eye iris (dark brown)
  a: '#DC9898',   // Lip / blush

  // Lola colors
  b: '#7A6E62',   // Lola hair base
  c: '#5C5044',   // Lola hair shadow
  d: '#4D4238',   // Lola hair deep
  e: '#8C7A68',   // Lola dress base
  f: '#6E5E4E',   // Lola dress shadow
  g: '#5E4E3E',   // Lola dress deep
  h: '#D4A878',   // Lola dress highlight

  // Maria colors
  i: '#2A2828',   // Maria hair base
  j: '#1E1C1C',   // Maria hair shadow
  k: '#121010',   // Maria hair deep
  l: '#2E4060',   // Maria uniform (navy) base
  m: '#223450',   // Maria uniform shadow
  n: '#3A5070',   // Maria uniform highlight
  o: '#D4A868',   // Maria accent (bag/tie)

  // Jeff colors
  p: '#3A4838',   // Jeff hair base
  q: '#2E3A2E',   // Jeff hair shadow
  r: '#1A2218',   // Jeff hair deep
  s: '#5A6A7A',   // Jeff pants base
  t: '#4A5A6A',   // Jeff pants shadow
  u: '#6A7A8A',   // Jeff pants highlight
  v: '#A09888',   // Jeff shoes

  // Shared uniform whites/creams
  w: '#F4F0E8',   // White uniform base
  x: '#ECE8E0',   // White uniform shadow
  y: '#E4E0D8',   // White uniform deep
  z: '#D8D4CC',   // White uniform dark
};

const PIXEL_SIZE = 6;

export function CharacterSprite({ spriteId, speaker }: CharacterSpriteProps) {
  const config = spriteId ? CHARACTER_PIXELS[spriteId] : undefined;
  const pngPath = spriteId ? PIXEL_PNGS[spriteId] : undefined;

  if (!spriteId && !speaker) return null;

  // Render pixel art PNG if available
  if (pngPath) {
    return (
      <div className="absolute bottom-24 left-4 sm:left-8 md:left-16 flex flex-col items-center animate-fade-in">
        <div className="image-pixel relative w-[192px] h-[288px]">
          <Image
            src={pngPath}
            alt={speaker ?? 'Character'}
            fill
            className="object-contain image-pixel"
            priority
            unoptimized
          />
          {/* Soft glow */}
          <div
            className="absolute inset-0 pointer-events-none"
            style={{
              background:
                'linear-gradient(180deg, rgba(13,12,10,0) 60%, rgba(13,12,10,0.4) 100%)',
            }}
          />
        </div>
        {speaker && (
          <div
            className="mt-2 px-3 py-1 rounded text-xs font-bold uppercase tracking-wider opacity-80"
            style={{
              backgroundColor: 'rgba(28,25,22,0.8)',
              color: '#C4863A',
            }}
          >
            {config?.label ?? speaker}
          </div>
        )}
      </div>
    );
  }

  if (!config) {
    // Fallback for unmapped sprites
    return (
      <div className="absolute bottom-24 left-4 sm:left-8 md:left-16 flex flex-col items-center animate-fade-in opacity-60">
        <div className="w-20 h-28 rounded-lg bg-storm-dim" />
        {speaker && (
          <div className="mt-2 px-3 py-1 rounded text-xs font-bold uppercase tracking-wider bg-storm-surface text-storm-dim">
            {speaker}
          </div>
        )}
      </div>
    );
  }

  const rows = config.pixels;
  const height = rows.length * PIXEL_SIZE;
  const width = (rows[0]?.length ?? 0) * PIXEL_SIZE;

  return (
    <div className="absolute bottom-24 left-4 sm:left-8 md:left-16 flex flex-col items-center animate-fade-in">
      {/* CSS pixel art fallback sprite */}
      <div
        className="image-pixel"
        style={{ width, height, position: 'relative' }}
      >
        {rows.map((row, y) =>
          row.map((pixel, x) => {
            if (pixel === ' ') return null;
            return (
              <div
                key={`${x}-${y}`}
                style={{
                  position: 'absolute',
                  top: y * PIXEL_SIZE,
                  left: x * PIXEL_SIZE,
                  width: PIXEL_SIZE,
                  height: PIXEL_SIZE,
                  backgroundColor: COLOR_MAP[pixel] ?? '#000',
                }}
              />
            );
          }),
        )}
        {/* Soft glow */}
        <div
          className="absolute inset-0"
          style={{
            background:
              'linear-gradient(180deg, rgba(13,12,10,0) 60%, rgba(13,12,10,0.4) 100%)',
            pointerEvents: 'none',
          }}
        />
      </div>

      {/* Name label */}
      {speaker && (
        <div
          className="mt-2 px-3 py-1 rounded text-xs font-bold uppercase tracking-wider opacity-80"
          style={{
            backgroundColor: 'rgba(28,25,22,0.8)',
            color: '#C4863A',
          }}
        >
          {config.label}
        </div>
      )}
    </div>
  );
}
