'use client';

import { useEffect, useRef } from 'react';
import Link from 'next/link';
import { SimulationProvider, useSimulation } from '@/lib/engine/simulation-context';
import { signalLabel } from '@/lib/engine/reflection';
import type { Case } from '@/lib/schema/case.schema';

/**
 * Entry point for the debrief route.
 *
 * The debrief page is a server component, so it mounts its own provider and
 * rehydrates the player's run from the saved decision IDs. Replaying those IDs
 * through the engine is what makes the profile identical to the one shown at
 * the end of the simulation.
 */
export function RunSummarySection({ caseData }: { caseData: Case }) {
  return (
    <SimulationProvider>
      <RunLoader caseData={caseData} />
    </SimulationProvider>
  );
}

function RunLoader({ caseData }: { caseData: Case }) {
  const { init } = useSimulation();
  const initialized = useRef(false);

  useEffect(() => {
    if (initialized.current) return;
    initialized.current = true;
    init(caseData);
  }, [caseData, init]);

  return <RunSummaryPanel caseId={caseData.id} />;
}

/**
 * Renders the player's Information Profile and rule-based reflection (§11, §12).
 *
 * The debrief route is a server component and cannot see the player's run,
 * which lives in client context. This component is the bridge. It renders the
 * `RunSummary` contract produced by the engine and adds no logic of its own —
 * all scoring and copy generation happens in `simulation-engine` / `reflection`.
 */
export function RunSummaryPanel({ caseId }: { caseId: string }) {
  const { runSummary, phase } = useSimulation();

  if (!runSummary || phase === 'loading') {
    return <PanelShell>Loading your run…</PanelShell>;
  }

  if (!runSummary.completed) {
    return (
      <PanelShell>
        <p className="text-storm-muted text-sm leading-relaxed">
          Your Information Profile appears here once you finish the case.
        </p>
        <Link
          href={`/cases/${caseId}/play`}
          className="mt-4 inline-block text-storm-accent text-sm font-bold hover:underline"
        >
          Continue the simulation →
        </Link>
      </PanelShell>
    );
  }

  const { profile, reflection, signalsDemonstrated, signalOpportunities } = runSummary;

  return (
    <div className="space-y-4">
      {profile && (
        <div className="rounded-xl border border-storm-dim/20 p-5">
          <p className="text-storm-dim text-xs uppercase tracking-wider font-bold">
            Your Information Profile
          </p>
          <h3 className="text-storm-accent font-bold text-base mt-1">{profile.title}</h3>
          <p className="text-storm-text text-sm leading-relaxed mt-2">{profile.description}</p>
        </div>
      )}

      <div className="rounded-xl border border-storm-dim/20 p-5 space-y-4">
        <p className="text-storm-dim text-xs uppercase tracking-wider font-bold">
          What your decisions showed
        </p>

        {reflection.map((line) => (
          <div key={line.signal}>
            <div className="flex items-baseline justify-between gap-3">
              <span className="text-storm-text text-sm font-bold capitalize">
                {signalLabel(line.signal)}
              </span>
              <span className="text-storm-dim text-xs shrink-0 tabular-nums">
                {line.demonstrated} of {line.opportunities}
              </span>
            </div>
            <div
              className="mt-1.5 h-1 w-full rounded-full bg-storm-surface overflow-hidden"
              role="img"
              aria-label={`${line.demonstrated} of ${line.opportunities} moments`}
            >
              <div
                className="h-full rounded-full bg-storm-accent"
                style={{
                  width: `${line.opportunities === 0 ? 0 : (line.demonstrated / line.opportunities) * 100}%`,
                }}
              />
            </div>
            <p className="text-storm-muted text-sm leading-relaxed mt-1.5">{line.text}</p>
          </div>
        ))}

        <p className="text-storm-dim text-xs italic pt-1">
          These indicators describe the habits your choices showed in this simulation. They are
          not a score, a grade, or a measure of real-world behaviour.
        </p>
      </div>

      <details className="rounded-xl border border-storm-dim/20 p-5">
        <summary className="text-storm-dim text-xs uppercase tracking-wider font-bold cursor-pointer">
          How this was calculated
        </summary>
        <p className="text-storm-muted text-sm leading-relaxed mt-3">
          Your profile is the sum of the behavioural values written on each option you chose.
          Nothing is generated by AI and nothing is random — the same choices always produce the
          same result.
        </p>
        <ul className="text-storm-dim text-xs mt-3 space-y-1">
          {Object.entries(runSummary.profileScores).map(([id, score]) => (
            <li key={id} className="tabular-nums">
              {id}: {score > 0 ? `+${score}` : score}
            </li>
          ))}
        </ul>
        <p className="text-storm-dim text-xs mt-3">
          Checks demonstrated:{' '}
          {Object.values(signalsDemonstrated).reduce((a, b) => a + b, 0)} of{' '}
          {Object.values(signalOpportunities).reduce((a, b) => a + b, 0)} opportunities.
        </p>
      </details>
    </div>
  );
}

function PanelShell({ children }: { children: React.ReactNode }) {
  return <div className="rounded-xl border border-storm-dim/20 p-5">{children}</div>;
}
